- name: Install Docker on Linux
  hosts: all
  become: true
  vars_files:
    - ../../inventory/secrets.yml
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: true
        upgrade: dist

    - name: Install dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: latest
        update_cache: true

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    - name: Install Docker
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Install Docker Compose plugin
      apt:
        name: docker-compose-plugin
        state: latest

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: true

    - name: Add current user to the Docker group (optional)
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true
