- name: Install Nomad on Linux
  hosts: all
  become: yes
  vars_files:
    - ../../inventory/secrets.yml

  tasks:
    - name: Update apt package index and install required dependencies
      apt:
        name:
          - wget
          - gpg
          - coreutils
        state: present
        update_cache: yes

    - name: Download HashiCorp GPG key
      get_url:
        url: https://apt.releases.hashicorp.com/gpg
        dest: /tmp/hashicorp-key.gpg
        mode: "0644"
      register: gpg_key_result

    - name: Convert GPG key to dearmored format
      shell: gpg --dearmor -o /tmp/hashicorp-keyring.gpg /tmp/hashicorp-key.gpg
      when: gpg_key_result.changed

    - name: Move dearmored key to /usr/share/keyrings
      command: mv /tmp/hashicorp-keyring.gpg /usr/share/keyrings/hashicorp-archive-keyring.gpg
      when: gpg_key_result.changed

    - name: Add HashiCorp repository
      copy:
        dest: /etc/apt/sources.list.d/hashicorp.list
        content: |
          deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main
        mode: "0644"

    - name: Install Nomad
      apt:
        name: nomad
        state: present
        update_cache: yes

    - name: Install Consul
      apt:
        name: consul
        state: present
        update_cache: yes
